server:
  # 服务端口
  port: 8091

spring:
  application:
    # 服务消费者
    name: zookeeper-consumer
  cloud:
    zookeeper:
      # zookeeper 连接地址
      connect-string: 192.168.0.10:2181
      discovery:
        register: false
        # zookeeper 节点
        root: /spring-cloud-service
      dependencies:
        # zookeeper 服务
        service-zookeeper:
          required: true
          path: /zookeeper-provider
          loadBalancerType: ROUND_ROBIN
