server:
  # 服务端口
  port: 8092

spring:
  application:
    # 服务提供者
    name: zookeeper-provider
  cloud:
    zookeeper:
      # zookeeper 连接地址
      connect-string: 192.168.0.188:2181
      discovery:
        # 是否启用
        enabled: true
        # 是否注册
        register: true
        # zookeeper 节点
        root: /spring-cloud-service