server:
  port: 8070

eureka:
  instance:
    # 设置主机名
    hostname: localhost

  client:
    # 表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    registerWithEureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    fetchRegistry: false
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

    #server:
    # 设置同步为空时的等待时间。默认 5 * MINUTES
    #waitTimeInMsWhenSyncEmpty: 0